export const languages = [
  { name: "English", code: "en" },
  { name: "Spanish", code: "es" },
  { name: "French", code: "fr" },
  { name: "Portuguese", code: "pt" },
  { name: "Italian", code: "it" },
  { name: "Romanian", code: "ro" },
  { name: "Dutch", code: "nl" },
  { name: "German", code: "de" },
  { name: "Russian", code: "ru" },
  { name: "Ukrainian", code: "uk" },
  { name: "Polish", code: "pl" },
  { name: "Czech", code: "cs" },
  { name: "Simplified Chinese", code: "zh-CN" },
  { name: "Traditional Chinese", code: "zh-TW" },
  { name: "Cantonese", code: "yue" },
  { name: "Literary Chinese", code: "lzh" },
  { name: "Japanese", code: "ja" },
  { name: "Korean", code: "ko" },
  { name: "Standard Arabic", code: "ar" },
  { name: "Egyptian Arabic", code: "arz" },
  { name: "North Levantine Arabic", code: "apc" },
  { name: "Sudanese Arabic", code: "apd" },
  { name: "Gulf Arabic", code: "afb" },
  { name: "Iraqi Arabic", code: "acm" },
  { name: "Hejazi Arabic", code: "acw" },
  { name: "Najdi Arabic", code: "ars" },
  { name: "Yemeni Arabic", code: "ayn" },
  { name: "Maghrebi Arabic", code: "ary" },
  { name: "Hassaniya Arabic", code: "mey" },
  { name: "Classical Arabic", code: "arb" },
  { name: "Hindi", code: "hi" },
  { name: "Sanskrit", code: "sa" },
  { name: "Bengali", code: "bn" },
  { name: "Telugu", code: "te" },
  { name: "Marathi", code: "mr" },
  { name: "Urdu", code: "ur" },
  { name: "Gujarati", code: "gu" },
  { name: "Tamil", code: "ta" },
  { name: "Bhojpuri", code: "bho" },
  { name: "Maithili", code: "mai" },
  { name: "Malayalam", code: "ml" },
  { name: "Indonesian", code: "id" },
  { name: "Javanese", code: "jv" },
  { name: "Tagalog", code: "tl" },
  { name: "Vietnamese", code: "vi" },
  { name: "Thai", code: "th" },
  { name: "Burmese", code: "my" },
  { name: "Sinhalese", code: "si" },
  { name: "Turkish", code: "tr" },
  { name: "Iranian Persian", code: "fa" },
  { name: "Pashto", code: "ps" },
  { name: "Amharic", code: "am" },
  { name: "Swahili", code: "sw" },
  { name: "Hausa", code: "ha" },
  { name: "Yoruba", code: "yo" },
  { name: "Igbo", code: "ig" },
  { name: "Somali", code: "so" },
  { name: "Oromo", code: "om" },
  { name: "Fula", code: "ff" },
  { name: "Welsh", code: "cy" },
  { name: "Scottish Gaelic", code: "gd" },
  { name: "Malay", code: "ms" },
  { name: "Filipino", code: "fil" },
  { name: "Hmong", code: "hmn" },
  { name: "Haitian Creole", code: "ht" },
  { name: "Khmer", code: "km" },
  { name: "Luxembourgish", code: "lb" },
  { name: "Lao", code: "lo" },
  { name: "Breton", code: "br" },
  { name: "Swedish", code: "sv" },
  { name: "Danish", code: "da" },
  { name: "Norwegian", code: "no" },
  { name: "Finnish", code: "fi" },
  { name: "Icelandic", code: "is" },
  { name: "Faroese", code: "fo" },
  { name: "Hungarian", code: "hu" },
  { name: "Greek", code: "el" },
  { name: "Ancient Greek", code: "grc" },
  { name: "Albanian", code: "sq" },
  { name: "Lithuanian", code: "lt" },
  { name: "Latvian", code: "lv" },
  { name: "Estonian", code: "et" },
  { name: "Kazakh", code: "kk" },
  { name: "Mongolian", code: "mn" },
  { name: "Uyghur", code: "ug" },
  { name: "Georgian", code: "ka" },
  { name: "Armenian", code: "hy" },
  { name: "Yiddish", code: "yi" },
  { name: "Hebrew", code: "he" },
  { name: "Basque", code: "eu" },
  { name: "Catalan", code: "ca" },
  { name: "Galician", code: "gl" },
  { name: "Maltese", code: "mt" },
  { name: "Vulgar Latin", code: "vla" },
  { name: "Classical Latin", code: "cla" },
  { name: "Punjabi", code: "pa" },
  { name: "Nepali", code: "ne" },
  { name: "Dari", code: "prs" },
  { name: "Zulu", code: "zu" },
  { name: "Xhosa", code: "xh" },
  { name: "Sesotho", code: "st" },
  { name: "Afrikaans", code: "af" },
  { name: "Kinyarwanda", code: "rw" },
  { name: "Sundanese", code: "su" },
  { name: "Malagasy", code: "mg" },
  { name: "Samoan", code: "sm" },
  { name: "Tongan", code: "to" },
  { name: "Tahitian", code: "ty" },
  { name: "Hawaiian", code: "haw" },
  { name: "Fijian", code: "fj" },
  { name: "Quechua", code: "qu" },
  { name: "Aymara", code: "ay" },
  { name: "Guarani", code: "gn" },
  { name: "Ido", code: "io" },
  { name: "Lojban", code: "jbo" },
  { name: "Pali", code: "pi" },
  { name: "Toki Pona", code: "tok" },
  { name: "Esperanto", code: "eo" },
  { name: "Scots", code: "sco" },
  { name: "Old Norse", code: "non" },
  { name: "British English", code: "en-GB" },
  { name: "Australian English", code: "en-AU" },
  { name: "Canadian English", code: "en-CA" },
  { name: "Old English", code: "ang" },
  { name: "Middle English", code: "enm" },
  { name: "Mexican Spanish", code: "es-MX" },
  { name: "Ladin", code: "lld" },
  { name: "Navajo", code: "nv" },
  { name: "Tibetan", code: "bo" },
  { name: "Tatar", code: "tt" },
  { name: "Latin", code: "la" },
  { name: "Slovak", code: "sk" },
  { name: "Slovene", code: "sl" },
  { name: "Serbo Croatian", code: "hbs" },
  { name: "Bulgarian", code: "bg" },
  { name: "Macedonian", code: "mk" },
  { name: "Occitan", code: "oc" },
  { name: "Sardinian", code: "sc" },
  { name: "Uzbek", code: "uz" },
  { name: "Kyrgyz", code: "ky" },
  { name: "Tajik", code: "tg" },
  { name: "Kannada", code: "kn" },
  { name: "Oriya", code: "or" },
  { name: "Cornish", code: "kw" },
  { name: "Corsican", code: "co" },
  { name: "Irish", code: "ga" },
  { name: "Belarusian", code: "be" },
  { name: "Azerbaijani", code: "az" },
  { name: "Sindhi", code: "sd" },
  { name: "Kashmiri", code: "ks" },
  { name: "Kurdish", code: "ku" },
  { name: "Turkmen", code: "tk" },
  { name: "Wolof", code: "wo" },
  { name: "Shona", code: "sn" },
  { name: "Moldovan", code: "mo" },
  { name: "Maori", code: "mi" },
  { name: "Manx", code: "gv" },
  { name: "Braille", code: "bra" },
  { name: "Shakespearean", code: "en-shk" },
  { name: "Luganda", code: "lg" },
  { name: "Croatian", code: "hr" },
  { name: "Serbian", code: "sr" },
  { name: "Bosnian", code: "bs" },
  { name: "Klingon", code: "tlh" },
  { name: "Dothraki", code: "dth" },
  { name: "International Phonetic Alphabet", code: "ipa" },
  { name: "Base64", code: "base64" },
  { name: "Emoji", code: "emoji" },
  { name: "Morse Code", code: "morse" },
  { name: "Yoda", code: "yoda" },
  { name: "Binary", code: "bin" }
];
