// This file exports all tools and categories for search
import { Image,Text, FileText, Calculator, Terminal, Palette, Brain, CloudLightning, Sparkles, FileImage, Cloud, Package, UserRound, HeadphonesIcon, Languages, MessageSquare, BarChart4, DollarSign, Sigma, ChartBar, Compass, GitCompare, FileSearch, Wand2, FileJson, FileCode, Code2, Video, FilePlus, FileEdit, Pencil, Globe, Link2, Type, BrainCircuit, KeyRound } from 'lucide-react';

export const tools = [
    {
        title: 'AI Chat',
        description: 'Chat with an AI assistant for help with various tasks',
        icon: MessageSquare,
        path: '/ai/ai-chat',
        category: 'AI',
        isNew: false,
        hasPro: true,
    },
    {
        title: 'Translation',
        description: 'Translate text between multiple languages with AI',
        icon: Languages,
        path: '/ai/translation',
        category: 'AI',
        isNew: false,
        hasPro: true,
    },
    {
        title: 'Text Humanizer',
        description: 'Make AI-generated text sound more human and natural',
        icon: Text,
        path: '/ai/text-humanizer',
        category: 'AI',
        hasPro: true,
        isNew: true,
    },
    {
        title: 'Text to Speech',
        description: 'Convert text to natural-sounding speech in multiple languages',
        icon: HeadphonesIcon,
        path: '/ai/text-to-speech',
        category: 'AI',
        isNew: true,
        hasPro: true,
    },
    {
        title: 'AI Detection',
        description: 'Detect whether text was written by AI or a human',
        icon: UserRound,
        path: '/ai/ai-detection',
        category: 'AI',
        isNew: false,
        hasPro: true,
    },
    {
      title: 'Scientific Calculator',
      description: 'Advanced calculator with scientific functions and formulas',
      icon: Calculator,
      path: '/calculators/scientific-calculator',
      category: 'Calculators',
      isNew: false,
      hasPro: false,
    },
    {
      title: 'Equations Calculator',
      description: 'Solve various mathematical equations and systems',
      icon: Sigma,
      path: '/calculators/equations-calculator',
      category: 'Calculators',
      isNew: false,
      hasPro: false,
    },
    {
      title: 'Graph Plotter',
      description: 'Plot and visualize mathematical functions and data',
      icon: ChartBar,
      path: '/calculators/graph-plotter',
      category: 'Calculators',
      hasPro: false,
      isNew: false,
    },
    {
      title: 'Unit Converter',
      description: 'Convert between different units of measurement',
      icon: Compass,
      path: '/calculators/unit-converter',
      category: 'Calculators',
      isNew: false,
      isPro: false,
    },
    {
      title: 'Currency Converter',
      description: 'Convert between different currencies with live rates',
      icon: DollarSign,
      path: '/calculators/currency-converter',
      category: 'Calculators',
      isNew: false,
      hasPro: false,
    },
    {
      title: 'Collatz Conjecture',
      description: 'Explore the famous Collatz Conjecture with visualization',
      icon: BarChart4,
      path: '/calculators/collatz-conjecture',
      category: 'Calculators',
      isNew: true,
      hasPro: false,
    },
    {
      title: 'Code Editor',
      description: 'Write and edit code with syntax highlighting and auto-completion',
      icon: Code2,
      path: '/code/code-editor',
      category: 'Code Tools',
      isNew: false,
      hasPro: true,
    },
    {
      title: 'Code Snap',
      description: 'Create beautiful code screenshots for sharing',
      icon: FileCode,
      path: '/code/code-snap',
      isNew: false,
      category: 'Code Tools',
      hasPro: false,
    },
    {
      title: 'JSON Validator',
      description: 'Validate and format JSON data',
      icon: FileJson,
      path: '/code/json-validator',
      category: 'Code Tools',
      isNew: false,
      hasPro: false,
    },
    {
      title: 'Code Formatter',
      description: 'Format and beautify code in various languages',
      icon: Wand2,
      path: '/code/code-formatter',
      category: 'Code Tools',
      isNew: false,
      hasPro: false,
    },
    {
      title: 'SEO Analyzer',
      description: 'Analyze your website for SEO optimization',
      icon: FileSearch,
      path: '/code/seo-analyzer',
      category: 'Code Tools',
      hasPro: true,
      isNew: false,
    },
    {
      title: 'Code Compare',
      description: 'Compare and find differences between code snippets',
      icon: GitCompare,
      path: '/code/code-compare',
      category: 'Code Tools',
      isNew: true,
      hasPro: false,
    },
    {
      title: 'Color generator',
      description: 'Generate and explore colors in different formats',
      icon: FileText,
      path: '/color/color-generator',
      category: 'Color Tools',
      isNew: false,
      hasPro: false,
    },
    {
      title: 'Gradient generator',
      description: 'Create beautiful CSS gradients for your web projects',
      icon: Sigma,
      path: '/color/gradient-generator',
      category: 'Color Tools',
      isNew: false,
      hasPro: false,
    },
    {
      title: 'PDF Editor',
      description: 'Edit, merge, split, and annotate PDF files with ease',
      icon: FileText,
      path: '/documents/pdf-editor',
      category: 'Documents',
      isNew: false,
      hasPro: false,
    },
    {
      title: 'Excel Editor',
      description: 'Create and edit spreadsheets online',
      icon: Sigma,
      path: '/documents/excel-editor',
      category: 'Documents',
      hasPro: false,
      isNew: false,
    },
    {
      title: 'Document Viewer',
      description: 'View various document formats online',
      icon: FileText,
      path: '/documents/doc-viewer',
      category: 'Documents',
      isNew: false,
      hasPro: true,
    },
    {
      title: 'Document Creator',
      description: 'Create new documents with templates and formatting options',
      icon: FilePlus,
      path: '/documents/doc-creator',
      category: 'Documents',
      isNew: false,
      hasPro: true,
    },
    {
      title: 'Image Editor',
      description: 'Edit and enhance your images with powerful tools',
      icon: Image,
      path: '/documents/image-editor',
      category: 'Documents',
      isNew: false,
      hasPro: false,
    },
    {
      title: 'Video Editor',
      description: 'Edit videos with trimming, effects, and more',
      icon: Video,
      path: '/documents/video-editor',
      category: 'Documents',
      hasPro: false,
      isNew: true,
    },
    {
      title: 'Document Types Converter',
      description: 'Convert between different document formats',
      icon: FileText,
      path: '/documents/converters/document-types-converter',
      category: 'Documents',
      isNew: true,
      hasPro: true,
    },
    {
      title: 'Image & Video Converter',
      description: 'Convert between different image and video formats',
      icon: FileImage,
      path: '/documents/converters/image-video-types-converter',
      category: 'Documents',
      isNew: false,
      hasPro: true,
    },
    {
      title: 'Mind Map',
      description: 'Visualize and organize your ideas using a dynamic mind mapping tool',
      icon: BrainCircuit,
      path: '/extra-tools/mind-maps',
      category: 'Extra Tools',
      isNew: true,
      hasPro: false,
    },
    {
      title: 'Password Tools',
      description: 'Generate strong passwords and evaluate password strength',
      icon: KeyRound,
      category: 'Extra Tools',
      path: '/extra-tools/password',
      isNew: false,
      hasPro: false,
    },
    {
      title: 'Text Case Converter',
      description: 'Convert text between uppercase, lowercase, title case, and more',
      icon: Type,
      path: '/extra-tools/textCase-converter',
      category: 'Extra Tools',
      isNew: false,
      hasPro: false,
    },
    {
      title: 'URL Shortener',
      description: 'Shorten long URLs for easier sharing and tracking',
      icon: Link2,
      path: '/extra-tools/url-shortners',
      category: 'Extra Tools',
      isNew: false,
      hasPro: true,
    },
    {
      title: 'Time Zone Converter',
      description: 'Easily convert time across different time zones',
      icon: Globe,
      path: '/extra-tools/timeZone-converter',
      category: 'Extra Tools',
      isNew: false,
      hasPro: false,
    },
    {
      title: 'Online Whiteboard',
      description: 'Collaborative drawing and planning',
      icon: Pencil,
      path: '/extra-tools/whiteboard',
      category: 'Extra Tools',
      isNew: false,
      hasPro: false,
    },
    {
      title: 'CV Maker',
      description: 'Create professional resumes',
      icon: FileEdit,
      path: '/extra-tools/cv-maker',
      category: 'Extra Tools',
      isNew: false,
      hasPro: false,
    }
];

export const categories = [
  {
    title: 'Documents',
    description: 'Edit, convert, and manage documents',
    icon: FileText,
    path: '/documents',
  },
  {
    title: 'Calculators',
    description: 'Perform various calculations',
    icon: Calculator,
    path: '/calculators',
  },
  {
    title: 'Code Tools',
    description: 'Developer utilities and helpers',
    icon: Terminal,
    path: '/code',
  },
  {
    title: 'Color Tools',
    description: 'Generate colors and palettes',
    icon: Palette,
    path: '/color',
  },
  {
    title: 'AI Tools',
    description: 'Artificial intelligence powered utilities',
    icon: Brain,
    path: '/ai',
  },
  {
    title: 'Cloud Storage',
    description: 'Store and access your files',
    icon: Cloud,
    path: '/cloud-storage',
  },
  {
    title: 'Extra Tools',
    description: 'Additional useful utilities',
    icon: Package,
    path: '/extra-tools',
  },
  {
    title: 'Pricing',
    description: 'View our pricing plans and features',
    icon: DollarSign,
    path: '/pricing',
  },
];
